//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.Libro_tienda = new HashSet<Libro_tienda>();
        }
    
        public string isbn { get; set; }
        public string desc_libro { get; set; }
        public int autor { get; set; }
        public int editorial { get; set; }
        public Nullable<int> idioma { get; set; }
        public int categoria { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> tapa { get; set; }
        public Nullable<int> sagas { get; set; }
        public string urlimagen { get; set; }
        public Nullable<int> npaginas { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Editoriales Editoriales { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro_tienda> Libro_tienda { get; set; }
        public virtual Sagas Sagas1 { get; set; }
        public virtual Tapa Tapa1 { get; set; }
        public virtual Tipo_Libro Tipo_Libro { get; set; }
    }
}
