//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiendas()
        {
            this.Libro_tienda = new HashSet<Libro_tienda>();
        }
    
        public int id_tienda { get; set; }
        public string desc_tienda { get; set; }
        public string direc_tienda { get; set; }
        public Nullable<int> tipo_tienda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro_tienda> Libro_tienda { get; set; }
        public virtual Tipo_Tienda Tipo_Tienda1 { get; set; }
    }
}
